[package]
name = "frameserver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bincode = "2.0.1"
shared_memory = "0.12.4"


[[test]]
name = "ipc"
harness = false
