[package]
name = "frameserver"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
shared_memory = "0.12.4"

[build-dependencies]
cbindgen = "0.28.0"

[lib]
crate-type = ["rlib", "staticlib"]

[[test]]
name = "ipc"
harness = false
