[package]
name = "frameserver"
version = "0.1.0"
edition = "2024"

[dependencies]
ciborium = "0.2.2"
serde = { version = "1.0.219", features = ["derive"] }
shared_memory = "0.12.4"


[[test]]
name = "ipc"
harness = false
