[package]
name = "mediafx"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bincode = "2.0"
shared_memory = "0.12"

[[test]]
name = "ipc"
harness = false
