# Copyright (C) 2025 Andrew Wason
# SPDX-License-Identifier: GPL-3.0-or-later

from collections.abc import Buffer, Sequence

class MediaFX:
    @property
    def frame_bytecount(self) -> int: ...
    @property
    def frame_size(self) -> tuple[int, int]: ...
    @property
    def frame_count(self) -> int: ...
    def render_frame(self, frames: Sequence[Buffer] | None = None) -> tuple[float, float, float, float]: ...
    def render_commit(self, rendered_frame: Buffer) -> None: ...
