[package]
name = "mediafx_client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
shared_memory = "0.12.4"
mediafx_common = { path = "../common" }
