[package]
name = "client_state"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mediafx_client = { path = "../../mediafx/client" }
