[package]
name = "mediafx_mixer2"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
mediafx_frei0r = { path = "../mediafx" }
