[package]
name = "mediafx_mixer3"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
mediafx = { path = "../mediafx" }
