[package]
name = "mediafx_mixer3"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "../build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
mediafx_frei0r = { path = "../mediafx" }
