name: frameserver-ci

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  frameserver-ci:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: rustup
        run: rustup update stable
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.4"
      - name: Lint
        run: |
          uv run --project clients/mediafx-py cargo fmt -- --check
          uv run --project clients/mediafx-py cargo clippy -- -D warnings

          cd clients/mediafx-py
          uv sync
          uv run ruff check
          uv run ruff format --check
          uv run mypy
      - name: Build
        run: |
          uv run --project clients/mediafx-py cargo build --all-targets --verbose
      - name: Run tests
        run: uv run --project clients/mediafx-py cargo test --verbose
      - name: Install ffmpeg
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install ffmpeg
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ffmpeg
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install ffmpeg-full
          else
            exit 1
          fi
        shell: bash
      - name: Run examples
        env:
          FREI0R_PATH: ${{ github.workspace }}/target/debug
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            PYSUFFIX=cmd
            echo -e "@echo off\n\rpython clients/mediafx-py/python/tests/color.py" > clients/mediafx-py/python/tests/color.cmd
            echo -e "@echo off\n\rpython clients/mediafx-py/python/tests/shift.py" > clients/mediafx-py/python/tests/shift.cmd
            source clients/mediafx-py/.venv/Scripts/activate
          else
            PYSUFFIX=py
            source clients/mediafx-py/.venv/bin/activate
          fi

          ffmpeg -f lavfi -i 'testsrc=duration=2:size=640x360:rate=30:decimals=2,drawbox=color=red:t=ih/16' -vf "frei0r=filter_name=mediafx_filter:filter_params=target/debug/examples/shift" -y frei0r_shift.mp4
          ffmpeg -f lavfi -i "frei0r_src=size=640x360:framerate=30:filter_name=mediafx_source:filter_params=target/debug/examples/color" -t 2 -y frei0r_color.mp4

          ffmpeg -f lavfi -i 'testsrc=duration=2:size=640x360:rate=30:decimals=2,drawbox=color=red:t=ih/16' -vf "frei0r=filter_name=mediafx_filter:filter_params=clients/mediafx-py/python/tests/shift.${PYSUFFIX}" -y python_shift.mp4
          ffmpeg -f lavfi -i "frei0r_src=size=640x360:framerate=30:filter_name=mediafx_source:filter_params=clients/mediafx-py/python/tests/color.${PYSUFFIX}" -t 2 -y python_color.mp4
