name: frameserver-ci

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  frameserver-ci:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: rustup
        run: rustup update stable
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Install ffmpeg
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt install ffmpeg
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install ffmpeg
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install ffmpeg-full
          else
            exit 1
          fi
        shell: bash
      - name: Run examples
        env:
          FREI0R_PATH: ${{ github.workspace }}/target/debug
          EXAMPLES_PATH: ${{ github.workspace }}/target/debug/examples
        shell: bash
        run: |
          # Refer to the plugins using 'libXXX' name for macOS/Linux
          # https://github.com/rust-lang/cargo/issues/1970
          if [ "$RUNNER_OS" == "Windows" ]; then
            PLUGINPREFIX=""
          else
            PLUGINPREFIX=lib
          fi
          ffmpeg -f lavfi -i 'testsrc=duration=2:size=640x360:rate=30:decimals=2,drawbox=color=red:t=ih/16' -vf "frei0r=filter_name=${PLUGINPREFIX}mediafx_filter:filter_params=${EXAMPLES_PATH}/shift" -y frei0r_shift.mp4
          ffmpeg -f lavfi -i "frei0r_src=size=640x360:framerate=30:filter_name=${PLUGINPREFIX}mediafx_source:filter_params=${EXAMPLES_PATH}/color" -t 2 -y frei0r_color.mp4
