name: frameserver-ci

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  frameserver-ci:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: rustup
        run: rustup update stable
      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
