name: Publish crate

on:
  push:
    tags:
      - v**
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Build distribution package
    environment: release
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: rustup update stable
      - name: Get version
        id: version
        run: |
          echo "crate=$(.github/workflows/get-version.sh mediafx)" >> "$GITHUB_OUTPUT"
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish
        if: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name == format('v{0}', steps.version.outputs.crate) }}
        run: cargo publish --package mediafx
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
